{
 "title": "WMI_Windows Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wmi_exporter_collector_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_exporter_collector_duration_seconds"
    }
   ]
  },
  {
   "title": "Logical_Disk_Read_Bytes_Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_read_bytes_total[5m])",
     "legendFormat": "Logical_disk_read_bytes_total"
    }
   ]
  },
  {
   "title": "Winser2016_CPU_Core_Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wmi_cpu_core_frequency_mhz", "legendFormat": "wmi_cpu_core_frequency_mhz" }
   ]
  },
  {
   "title": "Net_packets_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_net_packets_total[5m])",
     "legendFormat": "Net_packets_total"
    }
   ]
  }
 ]
}